using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pizza_Burger_Hub.Models
{
    [Table("Carts")]
    public class Cart
    {
        [Display(Name = "ID of the Cart")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Cart_Id { get; set; }

        [Display(Name = "Id of the User")]
        [Required]
        public int User_Id { get; set; }

        [Display(Name = "Id of the Product")]
        [Required]
        public int Product_Id { get; set; }

        [Required]
        [Display(Name = "Ordered Quantity")]
        public int Ordered_Quantity { get; set; }


        [Display(Name = "Order Total")]
        [Required]
        [Range(0.0, 50000.00, ErrorMessage = "{0} has to be between Rs. {1} and Rs. {2}")]
        public decimal Cost { get; set; }


        /// <summary>
        ///     The date time stamp when the record was created.
        /// </summary>
        /// <remarks>
        ///     This is marked as a "computed" column, to inform EF that the value for this column
        ///     would be generated by the Database during an INSERT operation, 
        ///     and the developer cannot assign a value to the field.
        ///     
        ///     However, to ensure that this is handled correctly, set the default value 
        ///     in the ApplicationDbContext class during the "OnModelCreating" method.
        /// </remarks>
        [Display(Name = "Created at")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreatedAt { get; set; }

        [Display(Name = "Payment Type")]
        [Column(TypeName = "varchar(20)")]
        public PaymentTypes Payment_Type { get; set; }

        [Required]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Display(Name = "Ordered_Status")]
        [Column(TypeName = "varchar(20)")]
        public OrderedStatuss Ordered_Status { get; set; }

        

    }
}
